// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoteApp.Backend.Core.Data;

#nullable disable

namespace VoteApp.Backend.Core.Migrations
{
    [DbContext(typeof(VoteAppDbContext))]
    [Migration("20231101153659_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VoteApp.Backend.Core.Data.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Candidates", "Core");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beta"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delta"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Omega"
                        });
                });

            modelBuilder.Entity("VoteApp.Backend.Core.Data.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("VoterId")
                        .IsUnique();

                    b.HasIndex("VoterId", "CandidateId")
                        .IsUnique();

                    b.ToTable("Votes", "Core");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateId = 1,
                            VoterId = 1
                        },
                        new
                        {
                            Id = 2,
                            CandidateId = 1,
                            VoterId = 2
                        },
                        new
                        {
                            Id = 3,
                            CandidateId = 3,
                            VoterId = 3
                        },
                        new
                        {
                            Id = 4,
                            CandidateId = 3,
                            VoterId = 4
                        },
                        new
                        {
                            Id = 5,
                            CandidateId = 5,
                            VoterId = 5
                        });
                });

            modelBuilder.Entity("VoteApp.Backend.Core.Data.Entities.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Voters", "Core");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beta"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delta"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Omega"
                        });
                });

            modelBuilder.Entity("VoteApp.Backend.Core.Data.Entities.Vote", b =>
                {
                    b.HasOne("VoteApp.Backend.Core.Data.Entities.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoteApp.Backend.Core.Data.Entities.Voter", "Voter")
                        .WithOne("Vote")
                        .HasForeignKey("VoteApp.Backend.Core.Data.Entities.Vote", "VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("VoteApp.Backend.Core.Data.Entities.Candidate", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("VoteApp.Backend.Core.Data.Entities.Voter", b =>
                {
                    b.Navigation("Vote")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
